/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-02-23 09:53:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.util.Random;

public final class AddEmployee0_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <HTML>\r\n");
      out.write("  <HEAD>\r\n");
      out.write("  \t<LINK href=\"styles.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("  \t<script LANGUAGE=\"Javascript\" SRC=\"Images/calender.js\"></script>\r\n");
      out.write("\t<SCRIPT LANGUAGE=\"JavaScript\"></SCRIPT>\r\n");
      out.write("<script src=\"jscal2.js\"></script>\r\n");
      out.write("<script src=\"en.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"jscal2.css\" />\r\n");
      out.write("\r\n");
      out.write("    <TITLE> Add Employee </TITLE>\r\n");
      out.write("\t<script LANGUAGE=\"Javascript\" SRC=\"Images/calender.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </HEAD>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "MultiLevelmenu.htm", out, false);
      out.write("<br><br><br>\r\n");
      out.write("\r\n");
      out.write("  <body Class=SC>\r\n");

	Integer IAuth =(Integer)session.getAttribute("auth");
	int auth= IAuth.intValue();
	System.out.println("===Authentication=="+auth);

if(auth==1){
	
      out.write("<H3 align=center><IMG SRC=\"Images/error.gif\" WIDTH=\"17\" HEIGHT=\"13\" BORDER=0 ALT=\"\">You are not authorized to access this page</H3>");

}
else{

      out.write("\t\r\n");
      out.write("  <FORM NAME=\"AddEmpForm\" onSubmit=\"return check()\" action=\"AddEmployee.jsp\">\r\n");
      out.write("   <CENTER>\r\n");
      out.write("\r\n");
      out.write("   <TABLE BORDER=\"0\" CELLSPACING=\"2\"  CELLPADDING=\"2\" >\r\n");
      out.write("\t   <TR class=row_title  ALIGN=\"center\">\r\n");
      out.write("\t   <TH COLSPAN=\"2\"> Add new Employee </TH>\r\n");
      out.write("\t   </TR>\r\n");
      out.write("\t   \r\n");
      out.write("\t   <TR class=row_even >\r\n");
      out.write("\t   <TD>EMPNO *</TD>\r\n");
      out.write("\t   ");

	  Connection con=(Connection)session.getAttribute("connection");
		Statement stmt =  con.createStatement();
		String SelQ = "Select max(EMPNO) from EmpMaster order by EMPNO";
		//System.out.println(SelQ);
		ResultSet rs=stmt.executeQuery(SelQ);
		
		rs.next();
	   
      out.write("\r\n");
      out.write("\t   <TD><INPUT TYPE=\"TEXT\" NAME=\"EMPNO\" value=\"");
      out.print((rs.getInt(1)+1) );
      out.write("\" \r\n");
      out.write("\t   SIZE=\"30\"    readonly=\"readonly\"></TD>\r\n");
      out.write("\t   </TR>\r\n");
      out.write("\t   <TR class=row_odd >\r\n");
      out.write("\t   <TD>EMPName *</TD>\r\n");
      out.write("\t   <TD><INPUT TYPE=\"TEXT\" NAME=\"EMPName\" SIZE=\"30\" ></TD>\r\n");
      out.write("\t   </TR>\r\n");
      out.write("\r\n");
      out.write("\t   <TR class=row_odd >\r\n");
      out.write("\t   <TD>MailID *</TD>\r\n");
      out.write("\t   <TD><INPUT TYPE=\"TEXT\" NAME=\"MailID\" SIZE=\"30\"></TD>\r\n");
      out.write("\t   </TR>\r\n");
      out.write("\r\n");
      out.write("\t   <TR class=row_odd >\r\n");
      out.write("\t   <TD>EMP_ADDRESS *</TD>\r\n");
      out.write("\t   <TD><TEXTAREA NAME=\"EMP_ADDRESS\" rows=\"5\" cols=\"20\" >\r\n");
      out.write("\t   </TEXTAREA></TD>\r\n");
      out.write("\t   </TR>\r\n");
      out.write("\r\n");
      out.write("\t   <TR class=row_even >\r\n");
      out.write("\t   <TD>PHONENO *</TD>\r\n");
      out.write("\t   <TD><INPUT TYPE=\"TEXT\" NAME=\"PHONENO\" SIZE=\"10\"></TD>\r\n");
      out.write("\t   </TR>\r\n");
      out.write("\r\n");
      out.write("\t   <TR class=row_even >\r\n");
      out.write("\t   <TD>CurrentLocation*</TD>\r\n");
      out.write("\t   <TD><select name=\"CurrentLocation\">\r\n");
      out.write("\t\t\t\t<option value=\"Bangalore\">-----</option>\r\n");
      out.write("\t\t\t\t<option value=\"Bangalore\">Bangalore</option>\t   \r\n");
      out.write("\t\t\t\t<option value=\"Hyderabad\">Hyderabad</option>\r\n");
      out.write("\t\t\t\t<option value=\"Pune\">Pune</option>\r\n");
      out.write("\t\t\t</select></TD>\r\n");
      out.write("\t   </TR>\r\n");
      out.write("\r\n");
      out.write("\t   <TR class=row_odd >\r\n");
      out.write("\t   <TD>JoiningDate </TD>\r\n");
      out.write("\t    <TD><input size=20 readonly id=\"JoiningDate\" name=\"JoiningDate\">\r\n");
      out.write("\t\t\t<img id=\"imgDate\" style=\"CURSOR: hand\"  height=\"16\" src=\"Images/CalDis.gif\" width=\"16\" border=\"0\" name=\"imgDate\" onMouseOver=\"fnEnableCalLookup(this)\" onMouseOut=\"fnDisableCalLookup(this)\" >\r\n");
      out.write("\r\n");
      out.write("\t\t<TR class=row_even >\r\n");
      out.write("\t\t\t<TD>Role</TD>\r\n");
      out.write("\t\t\t<TD>\r\n");
      out.write("\t\t\t\t<select name=\"Role\">\r\n");
      out.write("\t\t\t\t\t<option value=\"NA\">-----</option>\r\n");
      out.write("\t\t\t\t\t<option>General Manager</option>\t   \r\n");
      out.write("\t\t\t\t\t<option>Accounts Manager</option>\r\n");
      out.write("\t\t\t\t\t<option>Sales Manager</option>\t   \r\n");
      out.write("\t\t\t\t\t<option>Sales Representative</option>\r\n");
      out.write("\t\t\t\t\t<option>Accountant</option>\t   \r\n");
      out.write("\t\t\t\t\t<option>Accounts Assistant</option>\r\n");
      out.write("\t\t\t\t\t<option>Clerk</option>\t   \r\n");
      out.write("\t\t\t\t\t<option>Receptionist</option>\t   \r\n");
      out.write("\t\t\t\t\t<option>Security</option>\t   \r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR class=row_odd >\r\n");
      out.write("\t\t\t<TD>Qualification</TD>\r\n");
      out.write("\t\t\t<TD><INPUT TYPE=\"TEXT\" NAME=\"Qualification\"  SIZE=\"30\"></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR class=row_even >\r\n");
      out.write("\t\t\t<TD>Remarks</TD>\r\n");
      out.write("\t\t\t<TD><INPUT TYPE=\"TEXT\" NAME=\"Remarks\"   SIZE=\"30\"></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR class=row_odd  ALIGN=\"CENTER\">\r\n");
      out.write("\t\t\t<TD><INPUT TYPE=\"SUBMIT\" VALUE=\"Add\" ></TD>\r\n");
      out.write("\t\t\t<TD><INPUT TYPE=\"RESET\" VALUE=\"Reset\"></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("   </TABLE>\r\n");
      out.write("   </CENTER>\r\n");
      out.write("   </FORM>\r\n");
      out.write("   \r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("\t\t//<![CDATA[\r\n");
      out.write("\r\n");
      out.write("\t\tvar cal = Calendar.setup({\r\n");
      out.write("\t\t\tonSelect : function(cal) {\r\n");
      out.write("\t\t\t\tcal.hide()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tshowTime : true\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tcal.manageFields(\"imgDate\", \"JoiningDate\", \"%d/%m/%Y\");\r\n");
      out.write("\t\t/*   cal.manageFields(\"f_btn1\", \"f_date1\", \"%Y-%m-%d %I:%M %p\"); */\r\n");
      out.write("\t\t/*   cal.manageFields(\"f_btn2\", \"f_date2\", \"%b %e, %Y %I:%M %p\");\r\n");
      out.write("\t\t  cal.manageFields(\"f_btn3\", \"f_date3\", \"%e %B %Y %I:%M %p\");\r\n");
      out.write("\t\t  cal.manageFields(\"f_btn4\", \"f_date4\", \"%A, %e %B, %Y %I:%M %p\");\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\t//]]>\r\n");
      out.write("\t</script>\r\n");
      out.write("   \r\n");
      out.write("   </BODY> \r\n");
      out.write("   </HTML>\r\n");
      out.write(" ");

  }
  
      out.write(' ');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
